name: 'create-report'
description: 'An action to create a generic run report'

branding:
  icon: 'file-text'
  color: 'green'

# TODO: Specify version
inputs:
  title:
    description: "Title of the report"
    required: true
  path:
    description: "File path of the report."
    required: false
  format:
    description: "The data format of the summary either markdown or html."
    required: false
    default: "markdown"

runs:
  using: "composite"
  steps:

    - name: Cache ghchecks
      id: ghchecks-cache
      uses: actions/cache@v2
      with:
        path: /usr/local/bin/ghchecks
        key: ${{ runner.os }}-ghchecks-lib-cache

    - if: steps.ghchecks-cache.outputs.cache-hit != 'true'
      uses: fwal/setup-swift@v1.10.0
      with:
        swift-version: "5.6"

    - name: Install GHChecks
      if: steps.ghchecks-cache.outputs.cache-hit != 'true'
      run: make install
      shell: bash

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.12'
        cache: 'pip'

    - run: pip install -r requirements.txt
      shell: bash

    - name: Create report
      run: |
        ghchecks create-report \
        --report "${{ inputs.title }} " \
        --path "${{ inputs.path }}" \
        --format "${{ inputs.format }}" \
        --repository "${{ github.repository }}" \
        --head-sha "${{ github.event.pull_request.head.sha }}" \
        --github-token "${{ github.token }}"
      shell: bash
