name: 'create-report'
description: 'An action to create a generic run report'

branding:
  icon: 'file-text'
  color: 'green'

# TODO: Specify version
inputs:
  title:
    description: "Title of the report"
    required: true
  path:
    description: "File path of the report."
    required: false
  format:
    description: "The data format of the summary either markdown or html."
    required: false
    default: "markdown"

runs:
  using: "composite"
  steps:
    - name: Cache Pip
      id: pip-cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-hashFiles("**/requirements.txt")-v1

    - uses: fwal/setup-swift@v1.14.0
      with:
        swift-version: "5.6"

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.12'
        cache: 'pip'

    - run: pip install -r requirements.txt
      if: steps.pip-cache.outputs.cache-hit != 'true'
      shell: bash

    - name: Create report
      run: |
        swift run ghchecks create-report \
        --title "${{ inputs.title }} " \
        --path "${{ inputs.path }}" \
        --format "${{ inputs.format }}" \
        --repository "${{ github.repository }}" \
        --head-sha "${{ github.event.pull_request.head.sha }}" \
        --github-token "${{ github.token }}"
      shell: bash
